Key-Pair Authentication Setup:

Openssl setup
https://slproweb.com/products/Win32OpenSSL.html

openssl version

If it will not work , then add path C:\Program Files\OpenSSL-Win64\bin in system environment variable.

Generate Private Key:

# Verify in home directory
pwd

# Create a keys directory to store our key pair and navigate into it
mkdir keys; cd keys

# Generate a 2048-bit RSA private key and convert it to PKCS8 format — the format Snowflake expects
openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt

# Derive the corresponding public key from the private key
openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub

# Verify both key files have been created
ls

# Create the project folder & move the private key into the project folder

D:\Snowflake DBA Training\Data Loading and Unloading\SnowPipeStreaming

mv rsa_key.p8 "D:\Snowflake DBA Training\Data Loading and Unloading\SnowPipeStreaming";

# Output the public key content to the terminal — copy this to register against your Snowflake user
cat ../keys/rsa_key.pub

-- Register the public key against the user for key-pair authentication
ALTER USER SUNITALEARN91 SET RSA_PUBLIC_KEY='<PublicKey>';

-- Create the database and schema to house our streaming data
CREATE OR REPLACE DATABASE TRANSACTIONS_DB;
CREATE OR REPLACE SCHEMA TRANSACTIONS_SCHEMA;

-- Create the target table for incoming streaming transactions
-- Each column maps directly to the fields generated by the Python client
CREATE OR REPLACE TABLE TRANSACTIONS_DB.TRANSACTIONS_SCHEMA.TRANSACTIONS (
    transaction_id  VARCHAR        NOT NULL,  -- Unique identifier for each transaction (UUID)
    sequence        NUMBER         NOT NULL,  -- Monotonically increasing offset token
    merchant        VARCHAR,                  -- Merchant name e.g. Amazon, Tesco
    amount          FLOAT,                    -- Transaction amount
    currency        VARCHAR(3),               -- ISO currency code e.g. GBP, USD, EUR
    status          VARCHAR(10),              -- approved, declined, or pending
    ts              TIMESTAMP_NTZ             -- UTC timestamp, no timezone offset stored
);

-- Query the table ordered by sequence to verify data is landing correctly
SELECT * FROM TRANSACTIONS_DB.TRANSACTIONS_SCHEMA.TRANSACTIONS ORDER BY SEQUENCE DESC;

--Virtual environment setup in VISUAL STUDIO

Click Add Environment, choose Existing environment, and paste the path:C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\python.exe

Create the environment: python -m venv venv

Activate it
.\venv\Scripts\Activate.ps1

Install the snowflake package:

pip install snowflake-ingest snowflake-connector-python

pip install snowpipe-streaming

--High-Level Architecture
This script implements a continuous data producer that simulates streaming event data (credit card transactions) directly into Snowflake.
Instead of traditional batch loading (which writes files to a cloud stage and loads them every few minutes), this script utilizes the 
Snowpipe Streaming SDK. This allows rows to be written directly from your local computer's memory into your Snowflake table with sub-second latency.